import sys

def generate():
    code = """// Generated by script
#include "ApiData.h"
#include <cstring>
#include <cmath>
#include <algorithm>
#include <vector>

#ifdef _MSC_VER
#	define GAME_API __declspec(dllexport)
#else
#	define GAME_API __attribute__ ((visibility("default")))
#endif

// Helper functions ...
static int GetBoundedId(int cardId) {
    return (cardId > 0 && cardId <= 1999) ? cardId : 0;
}

static int GetEnergyValue(EnergyType type) {
    if (type == EnergyType::Colorless) return 0;
    return EnergyTypeIndex(type) - 1; // Check this!
}

extern "C" GAME_API void GetV6Observation(ApiData* data, int perspective, const int* pending_selection, int pending_count, V6ObservationBuffer* out_buf) {
    if (!data || !out_buf) return;
    std::memset(out_buf, 0, sizeof(V6ObservationBuffer));
    State& state = data->state;
    
    // ...
}
"""
    with open("pokemon-tcg-ai-battle/ptcg_engine/ptcgProgram 22/RelationalObservation.cpp", "w") as f:
        f.write(code)

if __name__ == "__main__":
    generate()
